apiVersion: v1
kind: ConfigMap
metadata:
  name: source-connect-config
  namespace: app
data:
  application.yaml: >-
    source:
      storage:
        type: local
        paths:
          # Record 3
          - file:///app/resources/logs/large.ndjson
          # Record 500
          - file:///app/resources/logs/mixed.ndjson
          # Record 10,000
          - file:///app/resources/logs/normal.ndjson
          # Total 10,503 Records!
        configs:
          recursive: true
          filters:
            #        - type: exclude
            #          expressions:
            #            - '.*empty.*'
            - type: extension
              expressions:
                - .ndjson
                - .csv
        s3: # AWS S3
          bucket: my-bucket
          region: ap-northeast-2

        blob: # Not yet supported
          container:

    processing:
      pipelines:
        - type: trim
        - type: skipBlank

    target:
      kafka:
        offsetTopic: offset-topic
        sinkTopic: sink-topic

    connect:
      workerCount: 1
      taskCount: 1

    offsetManager:
      baseUrl: http://offset-manager:8080
  
    server:
      port: 8080
  
    spring:
      kafka:
        bootstrap-servers:
          # When different namespace in Kubernetes
          - kafka-local-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        producer:
          acks: -1
          compression-type: zstd
          properties:
            compression.zstd.level: 1 # default: 3
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
            security.protocol: PLAINTEXT
            sasl.mechanism: PLAIN
            transactional.id: "s3-source-connector"
  
        consumer:
          max-poll-records: 50_000 # default: 1000
          isolation-level: read_committed
          properties:
            poll.ms: 100 # default: 100
            session.timeout.ms: 45_000 # default: 45_000
            fetch.max.bytes: 57671680  # default: 57671680 (55MB)
            max.partition.fetch.bytes: 57671680 # default: 1MB
            # static membership
            #        group.instance.id: stateless-group
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.LongDeserializer
            security.protocol: PLAINTEXT
            sasl.mechanism: PLAIN
  
        admin:
          security:
            protocol: PLAINTEXT
          properties:
            sasl.mechanism: PLAIN
  
  
    management:
      # /actuator/prometheus 노출
      endpoints:
        prometheus:
          enabled: true
        # By default, only the health endpoint is exposed over HTTP and JMX
        health:
          enabled: true
        # Actuator 페이지로 노출할 endpoint 에 prometheus 포함
        web:
          exposure:
            include: "prometheus,health,info,metrics"
