plugins {
  id 'java'
}

group = 'sourceconnect'
version = '0.9.0'

repositories {
  mavenCentral()
}

dependencies {
  testImplementation platform('org.junit:junit-bom:6.0.0')
  testImplementation('org.junit.jupiter:junit-jupiter')
  testImplementation("org.assertj:assertj-core:3.27.6")
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  compileOnly 'org.projectlombok:lombok:1.18.42'
  annotationProcessor 'org.projectlombok:lombok:1.18.42'
}

test {
  useJUnitPlatform()
}
